# Generated by Django 4.2.13 on 2025-03-12 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название товара"),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                ("full_description", models.TextField(verbose_name="Полное описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
        ),
    ]
