# Generated by Django 5.0.6 on 2025-11-20 12:00

from django.db import migrations

def create_manager_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Создаем группу "Менеджер"
    manager_group, created = Group.objects.get_or_create(name='Менеджер')

    # Получаем все модели, к которым мы хотим дать доступ
    models = [
        apps.get_model('admin', 'LogEntry'),
        apps.get_model('auth', 'User'),
        apps.get_model('contenttypes', 'ContentType'),
        apps.get_model('sessions', 'Session'),
        apps.get_model('app', 'Product'),
        apps.get_model('app', 'Review'),
        apps.get_model('app', 'Category'),
        apps.get_model('app', 'Order'),
        apps.get_model('app', 'OrderItem'),
        apps.get_model('app', 'Profile'),
    ]

    # Собираем все права для этих моделей (view, add, change, delete)
    permissions = []
    for model in models:
        content_type = ContentType.objects.get_for_model(model)
        model_permissions = Permission.objects.filter(content_type=content_type)
        permissions.extend(model_permissions)

    # Присваиваем права группе
    manager_group.permissions.set(permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_feedback_options_remove_feedback_message_and_more'),
        ('sessions', '0001_initial'),
        ('admin', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(create_manager_group),
    ]