# Generated by Django 5.0.6 on 2025-11-27 08:00

from django.db import migrations
from django.utils.text import slugify
from transliterate import slugify as transliterate_slugify

def create_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')

    # Main Categories
    electrical_tools, _ = Category.objects.get_or_create(
        name="Электроинструменты",
        slug=transliterate_slugify("Электроинструменты")
    )
    petrol_tools, _ = Category.objects.get_or_create(
        name="Бензоинструменты",
        slug=transliterate_slugify("Бензоинструменты")
    )
    measuring_tools, _ = Category.objects.get_or_create(
        name="Измерительные инструменты",
        slug=transliterate_slugify("Измерительные инструменты")
    )

    # Subcategories for Электроинструменты
    Category.objects.get_or_create(
        name="Дрели",
        slug=transliterate_slugify("Дрели"),
        parent=electrical_tools
    )
    Category.objects.get_or_create(
        name="Шуруповерты",
        slug=transliterate_slugify("Шуруповерты"),
        parent=electrical_tools
    )
    Category.objects.get_or_create(
        name="Электротриммеры",
        slug=transliterate_slugify("Электротриммеры"),
        parent=electrical_tools
    )
    Category.objects.get_or_create(
        name="Болгарки",
        slug=transliterate_slugify("Болгарки"),
        parent=electrical_tools
    )

    # Subcategories for Бензоинструменты
    Category.objects.get_or_create(
        name="Генераторы",
        slug=transliterate_slugify("Генераторы"),
        parent=petrol_tools
    )
    Category.objects.get_or_create(
        name="Бензопилы",
        slug=transliterate_slugify("Бензопилы"),
        parent=petrol_tools
    )
    Category.objects.get_or_create(
        name="Косилки",
        slug=transliterate_slugify("Косилки"),
        parent=petrol_tools
    )
    Category.objects.get_or_create(
        name="Снегоуборочные машины",
        slug=transliterate_slugify("Снегоуборочные машины"),
        parent=petrol_tools
    )
    Category.objects.get_or_create(
        name="Триммеры",
        slug=transliterate_slugify("Триммеры"),
        parent=petrol_tools
    )

    # Subcategories for Измерительные инструменты
    Category.objects.get_or_create(
        name="Лазерные уровни",
        slug=transliterate_slugify("Лазерные уровни"),
        parent=measuring_tools
    )
    Category.objects.get_or_create(
        name="Рулетки",
        slug=transliterate_slugify("Рулетки"),
        parent=measuring_tools
    )
    Category.objects.get_or_create(
        name="Дальномер",
        slug=transliterate_slugify("Дальномер"),
        parent=measuring_tools
    )
    Category.objects.get_or_create(
        name="Тепловизоры",
        slug=transliterate_slugify("Тепловизоры"),
        parent=measuring_tools
    )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_category_options_category_parent'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]