# Generated by Django 5.2.8 on 2025-11-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'В корзине'), ('PAID', 'Оплачен'), ('ASSEMBLING', 'Собирается'), ('SHIPPED', 'Отправлен'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='CART', max_length=10, verbose_name='Статус'),
        ),
    ]
