# Generated by Django 5.2.8 on 2025-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'В корзине'), ('PAID', 'Оплачен'), ('ASSEMBLING', 'Собирается'), ('SHIPPED', 'Отправлен'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен'), ('DEFECT_RETURN', 'Возврат по браку')], default='CART', max_length=20, verbose_name='Статус'),
        ),
    ]
