# Generated by Django 5.2.8 on 2025-11-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by_user',
            field=models.BooleanField(default=False, verbose_name='Отменен пользователем'),
        ),
    ]
