# Generated by Django 5.2.8 on 2025-12-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_characteristic_remove_product_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
