# Generated by Django 5.2.8 on 2025-12-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('PICKUP', 'Самовывоз'), ('DELIVERY_POINT', 'Доставка в пункт выдачи'), ('HOME_DELIVERY', 'Доставка на дом')], max_length=20, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD_ONLINE', 'Картой онлайн'), ('CARD_ON_DELIVERY', 'Картой при получении'), ('CASH_ON_DELIVERY', 'Наличными при получении')], max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт выдачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'В корзине'), ('AWAITING_PAYMENT', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('ASSEMBLING', 'Собирается'), ('SHIPPED', 'Отправлен'), ('DELIVERING', 'В процессе доставки'), ('AWAITING_PICKUP', 'Ожидает в пункте выдачи'), ('ARRIVED', 'Прибыл'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен'), ('DEFECT_RETURN', 'Возврат по браку')], default='CART', max_length=20, verbose_name='Статус'),
        ),
    ]
