# Generated by Django 4.2.13 on 2026-03-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
    ]
