# Generated by Django 4.2.13 on 2026-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_profile_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Артикул (SKU)",
            ),
        ),
    ]
