# Generated by Django 4.2.13 on 2026-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_add_old_price_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="HEX-код цвета, например, #FF5733",
                max_length=7,
                null=True,
                verbose_name="Цвет бренда",
            ),
        ),
    ]
