# Generated by Django 4.2.13 on 2026-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_brand_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon class (например, 'fas fa-cog')",
                max_length=50,
                verbose_name="Иконка",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Изображение категории",
            ),
        ),
    ]
