# Generated by Django 4.2.13 on 2026-03-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_category_icon_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="HEX-код цвета, например, #FF5733",
                max_length=7,
                verbose_name="Цвет иконки",
            ),
        ),
    ]
