# Generated by Django 4.2.13 on 2026-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Количество покупок"
            ),
        ),
    ]
