# Generated by Django 4.2.13 on 2026-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_product_purchase_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок акции"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подзаголовок"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "discount",
                    models.PositiveIntegerField(default=0, verbose_name="Скидка (%)"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Ссылка (URL или имя маршрута)",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        default="Подробнее", max_length=50, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-percent",
                        max_length=50,
                        verbose_name="Иконка (Font Awesome)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF6B35", max_length=7, verbose_name="Цвет фона (HEX)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="promotions/",
                        verbose_name="Фоновое изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=False, verbose_name="Постоянная акция"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на главной"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
