# Generated by Django 4.2.13 on 2026-03-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="cons",
            field=models.TextField(blank=True, default="", verbose_name="Недостатки"),
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.IntegerField(default=0, verbose_name="Полезно"),
        ),
        migrations.AddField(
            model_name="review",
            name="not_helpful_count",
            field=models.IntegerField(default=0, verbose_name="Не полезно"),
        ),
        migrations.AddField(
            model_name="review",
            name="pros",
            field=models.TextField(blank=True, default="", verbose_name="Достоинства"),
        ),
        migrations.AddField(
            model_name="review",
            name="video_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Ссылка на видео"
            ),
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="reviews/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.review",
                    ),
                ),
            ],
        ),
    ]
