# Generated by Django 4.2.13 on 2026-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_reviewvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Уровень"),
        ),
        migrations.AddField(
            model_name="profile",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Баллы"),
        ),
    ]
