# Generated by Django 4.2.13 on 2026-06-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_profile_birth_date_profile_level_profile_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroCarouselSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок слайда"),
                ),
                ("subtitle", models.TextField(blank=True, verbose_name="Текст слайда")),
                (
                    "button_text",
                    models.CharField(
                        default="Подробнее", max_length=50, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        default="/catalog/",
                        max_length=200,
                        verbose_name="Ссылка кнопки",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carousel/",
                        verbose_name="Изображение (опционально)",
                    ),
                ),
                (
                    "bg_gradient_start",
                    models.CharField(
                        default="#FF6B00",
                        max_length=7,
                        verbose_name="Начало градиента (HEX)",
                    ),
                ),
                (
                    "bg_gradient_end",
                    models.CharField(
                        default="#FF9500",
                        max_length=7,
                        verbose_name="Конец градиента (HEX)",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=7,
                        verbose_name="Цвет текста (HEX)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Слайд карусели",
                "verbose_name_plural": "Слайды карусели",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="level",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="points",
        ),
    ]
