# Generated by Django 4.2.13 on 2026-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_herocarouselslide_remove_profile_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herocarouselslide",
            name="tag",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Маленький ярлык (напр. 'Акция', 'Новинка')",
            ),
        ),
    ]
