# Generated by Django 4.2.13 on 2026-06-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_herocarouselslide_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CART", "В корзине"),
                    ("CREATED", "Создан"),
                    ("ASSEMBLING", "В сборке"),
                    ("READY_FOR_PICKUP", "Готов к выдаче"),
                    ("COMPLETED", "Выдан и оплачен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="CART",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
