# Generated by Django 4.2.13 on 2026-06-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_stock_reduced",
            field=models.BooleanField(default=False, verbose_name="Склад обновлен"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CART", "В корзине"),
                    ("CREATED", "Оформлен"),
                    ("ASSEMBLING", "В сборке"),
                    ("READY_FOR_PICKUP", "Готов к выдаче"),
                    ("COMPLETED", "Выдан и оплачен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="CART",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
