# Generated by Django 4.2.13 on 2026-06-23 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_order_is_stock_reduced_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocode",
            options={},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_preorder",
            field=models.BooleanField(default=False, verbose_name="Под заказ"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="max_uses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="min_order_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="used_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
