# Generated by Django 4.2.13 on 2026-08-21 15:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_alter_promocode_options_orderitem_is_preorder_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characteristic",
            options={
                "ordering": ["name"],
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Количество на складе"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=app.models.get_product_image_path, verbose_name="Изображение"
            ),
        ),
    ]
