# Generated by Django 4.2.13 on 2026-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_characteristic_options_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="package_contents",
            field=models.TextField(blank=True, null=True, verbose_name="Комплектация"),
        ),
    ]
