# Generated by Django 4.2.13 on 2026-09-15 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_product_package_contents"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Первый сбой"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Последний сбой",
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(max_length=100, verbose_name="Тип ошибки"),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Шаблон адреса"
                    ),
                ),
                (
                    "method",
                    models.CharField(blank=True, max_length=10, verbose_name="Метод"),
                ),
                (
                    "stack",
                    models.TextField(
                        blank=True, verbose_name="Файлы, функции и строки"
                    ),
                ),
                (
                    "occurrences",
                    models.PositiveIntegerField(default=1, verbose_name="Повторений"),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Разобрано"),
                ),
            ],
            options={
                "verbose_name": "Сбой",
                "verbose_name_plural": "Журнал сбоев",
                "ordering": ["-last_seen"],
            },
        ),
    ]
