# Generated by Django 5.2.17 on 2026-10-05 09:57

import app.price_sync.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_error_journal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Постоянная скидка, %",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Цена обновлена"
            ),
        ),
        migrations.CreateModel(
            name="PriceImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("supplier_xlsx", "Прайс поставщика"),
                            ("manual", "Ручное изменение"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        storage=app.price_sync.storage.PrivatePriceImportStorage(),
                        upload_to=app.price_sync.storage.price_import_upload_to,
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_sha256",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("supplier", models.CharField(default="stiooo", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("ready", "Готов к применению"),
                            ("applied", "Применён"),
                            ("rolled_back", "Отменён"),
                            ("failed", "Ошибка"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("matched_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("review_rows", models.PositiveIntegerField(default=0)),
                ("changed_rows", models.PositiveIntegerField(default=0)),
                ("increased_rows", models.PositiveIntegerField(default=0)),
                ("decreased_rows", models.PositiveIntegerField(default=0)),
                ("anomaly_rows", models.PositiveIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_price_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rolled_back_price_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_price_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Обновление цен",
                "verbose_name_plural": "Обновление цен",
                "ordering": ("-created_at", "-pk"),
                "permissions": [
                    ("preview_priceimport", "Can create price import previews"),
                    ("create_manual_priceimport", "Can create manual price batches"),
                    ("resolve_priceimport", "Can resolve price import rows"),
                    ("apply_priceimport", "Can apply price imports"),
                    ("rollback_priceimport", "Can rollback price imports"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("source_sku", models.CharField(blank=True, max_length=100)),
                ("source_brand", models.CharField(blank=True, max_length=200)),
                ("source_title", models.CharField(max_length=500)),
                (
                    "source_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("candidate_product_ids", models.JSONField(blank=True, default=list)),
                ("match_method", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Сопоставлен"),
                            ("needs_review", "Требует проверки"),
                            ("skipped", "Пропущен"),
                            ("invalid", "Некорректен"),
                        ],
                        max_length=16,
                    ),
                ),
                ("diagnostic_code", models.CharField(blank=True, max_length=64)),
                (
                    "before_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "before_old_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "before_discount_percent",
                    models.PositiveSmallIntegerField(null=True),
                ),
                ("before_price_updated_at", models.DateTimeField(null=True)),
                (
                    "after_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "after_old_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("after_discount_percent", models.PositiveSmallIntegerField(null=True)),
                ("after_price_updated_at", models.DateTimeField(null=True)),
                ("anomaly_confirmed", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="app.priceimport",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_import_rows",
                        to="app.product",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка обновления цен",
                "verbose_name_plural": "Строки обновления цен",
                "ordering": ("row_number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("price_import", "row_number"),
                        name="uniq_price_import_row_number",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("product__isnull", False)),
                        fields=("price_import", "product"),
                        name="uniq_price_import_product",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierProductLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(default="stiooo", max_length=32)),
                ("source_sku", models.CharField(blank=True, max_length=100)),
                ("normalized_brand", models.CharField(blank=True, max_length=200)),
                ("normalized_title", models.CharField(blank=True, max_length=500)),
                ("numeric_signature", models.JSONField(blank=True, default=list)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_links",
                        to="app.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь с товаром поставщика",
                "verbose_name_plural": "Связи с товарами поставщика",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "product"),
                        name="uniq_supplier_product_link",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("source_sku", ""), _negated=True),
                        fields=("supplier", "source_sku"),
                        name="uniq_supplier_nonempty_sku",
                    ),
                ],
            },
        ),
    ]
