# Generated by Django 5.2.17 on 2026-10-05 11:22

import app.price_sync.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_price_sync"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="priceimport",
            name="anomaly_rows",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Изменение более 50%"
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="applied_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата применения"
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_price_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Применил",
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="changed_rows",
            field=models.PositiveIntegerField(default=0, verbose_name="Изменится"),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="decreased_rows",
            field=models.PositiveIntegerField(default=0, verbose_name="Подешевеет"),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="failure_code",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Код ошибки"
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="file_sha256",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="SHA-256 файла",
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="increased_rows",
            field=models.PositiveIntegerField(default=0, verbose_name="Подорожает"),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="matched_rows",
            field=models.PositiveIntegerField(default=0, verbose_name="Сопоставлено"),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя файла"
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="review_rows",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Требуют проверки"
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="rolled_back_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отмены"
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="rolled_back_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rolled_back_price_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отменил",
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="skipped_rows",
            field=models.PositiveIntegerField(default=0, verbose_name="Пропущено"),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="source_file",
            field=models.FileField(
                blank=True,
                storage=app.price_sync.storage.PrivatePriceImportStorage(),
                upload_to=app.price_sync.storage.price_import_upload_to,
                verbose_name="Файл прайса",
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("supplier_xlsx", "Прайс поставщика"),
                    ("manual", "Ручное изменение"),
                ],
                max_length=16,
                verbose_name="Тип источника",
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("ready", "Готов к применению"),
                    ("applied", "Применён"),
                    ("rolled_back", "Отменён"),
                    ("failed", "Ошибка"),
                ],
                default="draft",
                max_length=16,
                verbose_name="Состояние",
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="supplier",
            field=models.CharField(
                default="stiooo", max_length=32, verbose_name="Поставщик"
            ),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="total_rows",
            field=models.PositiveIntegerField(default=0, verbose_name="Всего строк"),
        ),
        migrations.AlterField(
            model_name="priceimport",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_price_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Загрузил",
            ),
        ),
    ]
