# Generated by Django 5.2.17 on 2026-10-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_localize_price_import_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priceimport",
            name="file_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="SHA-256 файла",
            ),
        ),
    ]
